import os
import uuid
from pathlib import Path

from vertexai.preview.vision_models import ImageGenerationModel

def generate_image_from_prompt(prompt: str) -> str:
    """
    Generates an image from a text prompt using Vertex AI Imagen.
    
    Args:
        prompt: The text prompt describing the image to generate.
        
    Returns:
        The absolute path to the saved image file.
    """
    # model or latest
    model = ImageGenerationModel.from_pretrained("imagegeneration@006")
    
    images = model.generate_images(
        prompt=prompt,
        number_of_images=1,
        language="en",
        aspect_ratio="1:1",
        safety_filter_level="block_some",
        person_generation="allow_adult",
    )
    
    if not images:
        raise RuntimeError("No image generated by Vertex AI.")
        
    # Ensure artifacts directory exists
    artifact_dir = Path(os.getcwd()) / "artifacts" / "generated_images"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    
    filename = f"{uuid.uuid4()}.png"
    filepath = artifact_dir / filename
    
    images[0].save(location=str(filepath), include_generation_parameters=False)
    
    return str(filepath)
