apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: __SERVICE_STAGING__
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: dashboard-image
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: staging
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "TRUE"
            - name: GOOGLE_CLOUD_PROJECT
              value: videogenerator-482919
            - name: GOOGLE_CLOUD_LOCATION
              value: us-central1
