apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: agent-dashboard

manifests:
  rawYaml: []

deploy:
  cloudrun: {}

profiles:
  - name: staging
    manifests:
      rawYaml:
        - frontend-staging.yaml

  - name: production
    manifests:
      rawYaml:
        - frontend-production.yaml
