"""Generate docs from command/help and API source-of-truth."""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
from pathlib import Path

from fastapi.routing import APIRoute

from dashboard_api.server import create_app

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "GENERATED_REFERENCE.md"


def _normalize_output(text: str) -> str:
    lines = text.replace("\r\n", "\n").split("\n")
    normalized: list[str] = []
    for line in lines:
        stripped = line.strip()
        if len(stripped) >= 2 and stripped.startswith('"') and stripped.endswith('"'):
            normalized.append(stripped[1:-1])
        else:
            normalized.append(line.rstrip())
    return "\n".join(normalized).strip() + "\n"


def _run_command(command: list[str]) -> str:
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    )
    return _normalize_output(result.stdout)


def _capture_make_help() -> str:
    return _run_command(["make", "help"])


def _capture_powershell_help() -> str:
    candidates: list[list[str]] = []

    if platform.system() == "Windows":
        candidates.append(["pwsh", "-File", "./make.ps1", "help"])
        candidates.append(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", "./make.ps1", "help"]
        )
    else:
        candidates.append(["pwsh", "-File", "./make.ps1", "help"])

    last_error: Exception | None = None
    for candidate in candidates:
        try:
            return _run_command(candidate)
        except Exception as exc:  # pragma: no cover - fallback chain
            last_error = exc

    raise RuntimeError("Failed to capture make.ps1 help output") from last_error


def _route_rows() -> list[tuple[str, str, str, str]]:
    app = create_app()
    rows: list[tuple[str, str, str, str]] = []

    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue

        if not (route.path.startswith("/api") or route.path == "/health"):
            continue

        methods = sorted(method for method in route.methods if method not in {"HEAD", "OPTIONS"})
        method_text = ", ".join(methods)
        tags = ", ".join(route.tags) if route.tags else "-"
        rows.append((method_text, route.path, route.name, tags))

    rows.sort(key=lambda row: (row[1], row[0]))
    return rows


def _render_markdown(make_help: str, ps_help: str) -> str:
    route_rows = _route_rows()

    lines: list[str] = [
        "# Generated Reference",
        "",
        "> Generated by `scripts/generate_reference_docs.py`. Do not edit manually.",
        "",
        "## API Endpoint Table",
        "",
        "| Methods | Path | Handler | Tags |",
        "| --- | --- | --- | --- |",
    ]

    for methods, path, handler, tags in route_rows:
        lines.append(f"| `{methods}` | `{path}` | `{handler}` | `{tags}` |")

    lines.extend(
        [
            "",
            "## Make Help Output",
            "",
            "```text",
            make_help.rstrip("\n"),
            "```",
            "",
            "## PowerShell Help Output",
            "",
            "```text",
            ps_help.rstrip("\n"),
            "```",
            "",
        ]
    )

    return "\n".join(lines)


def generate(check: bool, output: Path) -> int:
    make_help = _capture_make_help()
    ps_help = _capture_powershell_help()
    rendered = _render_markdown(make_help=make_help, ps_help=ps_help)

    if check:
        if not output.exists():
            print(f"Generated doc missing: {output}")
            return 1

        current = output.read_text(encoding="utf-8")
        if current != rendered:
            print(f"Generated reference docs are stale: {output}")
            print("Run: uv run python scripts/generate_reference_docs.py")
            return 1
        print(f"Generated reference docs are up to date: {output}")
        return 0

    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote generated reference docs: {output}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate docs reference artifacts.")
    parser.add_argument("--check", action="store_true", help="Fail if generated output is stale.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    output = args.output if args.output.is_absolute() else REPO_ROOT / args.output
    return generate(check=args.check, output=output)


if __name__ == "__main__":
    sys.exit(main())
