import logging
import os
import sys

from google import genai
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# Setup Logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


# Config (Reuse existing pattern)
class Config(BaseSettings):
    gemini_api_key: str = Field(..., alias="GEMINI_API_KEY")

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore"
    )


def main():
    try:
        config = Config()
        client = genai.Client(api_key=config.gemini_api_key)

        logger.info("Fetching model list from Google Gen AI API...")
        models = list(client.models.list())

        gemini_models = [m for m in models if "gemini" in m.name.lower()]

        # Sort for better readability
        gemini_models.sort(key=lambda x: x.name)

        if not gemini_models:
            logger.warning("No Gemini models found!")
            return

        docs_path = os.path.join(
            os.path.dirname(__file__), "../../../docs/available_models.md"
        )
        docs_path = os.path.abspath(docs_path)

        logger.info(f"Writing {len(gemini_models)} models to {docs_path}...")

        with open(docs_path, "w", encoding="utf-8") as f:
            f.write("# Available Gemini Models\n\n")
            f.write(
                "This list is automatically generated by `manage_documentation` skill.\n\n"
            )
            f.write("| Model Name | Display Name | Description |\n")
            f.write("| :--- | :--- | :--- |\n")

            for m in gemini_models:
                # Handle optional fields gracefully
                display_name = getattr(m, "display_name", "N/A")
                description = getattr(m, "description", "N/A").replace("\n", " ")
                # Truncate long descriptions
                if len(description) > 100:
                    description = description[:97] + "..."

                f.write(f"| `{m.name}` | {display_name} | {description} |\n")

        logger.info("Successfully updated available_models.md")

    except Exception as e:
        logger.error(f"Failed to update models: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
